name: Bug Report
description: Create a bug report for the PixelExperience team
labels: ['template: bug']
body:
  - type: markdown
    attributes:
      value: |
        What not to report:
        - Bugs in unofficial builds or anything not downloaded from our [Official Website](https://get.pixelexperience.org/)
        - Missing Builds
        - Problems with the website
        - Feature requests

        Make sure not to use extra mods when reporting a problem (for example: Magisk)
        If you need help please check our Telegram group at https://t.me/pixelexperiencechat
  - type: input
    attributes:
      label: Build Date
      description: |
        Anything that can help us identify the build you are using
        Example: ```PixelExperience_raphael-10.0-20201218-0409-OFFICIAL```
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Device
      multiple: false
      options:
        - 'Select one'
        - 'redfin'
        - 'barbet'
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Version
      multiple: false
      options:
        - 'Select one'
        - 'thirteen'
        - 'thirteen_plus'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior, please provide a clear description of how to reproduce the issue, based on the linked minimal reproduction. Screenshots can be provided in the issue body below. If using code blocks, make sure that [syntax highlighting is correct](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting) and double check that the rendered preview is not broken.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Possible Solution
      description: Not obligatory, but suggest a fix/reason for the bug
    validations:
      required: false
  - type: markdown
    attributes:
      value: Before posting the issue go through the steps you've written down to make sure the steps provided are detailed and clear.
