name: Bug Report
description: Create a bug report for the PixelExperience team
labels: ['template: bug']
body:
  - type: textarea
    attributes:
      label: Provide environment information
      description: Please run `next info` in the root directory of your project and paste the results. You might need to use `npx --no-install next info` if next is not in the current PATH.
      render: bash
    validations:
      required: true
